name: CI - Build and Testing 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-testing:
    name: Build and Testing
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.DB_USER_STG }}" > .env
          echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD_STG }}" >> .env
          echo "POSTGRES_DB=${{ secrets.DB_DBNAME_STG }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.DB_HOST_STG }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.DB_PORT_STG }}" >> .env

      - name: Install testing dependencies
        run: |
          pip install -r testing/requirements.txt

      - name: Build and Run Container
        run: |
          sudo docker compose up database app-stg --build --detach
          
      - name: Testing
        run: |
            pytest testing/test.py